[project]
name = "sprak"
version = "2.0.0"
description = "Pack sprites into a texture atlas"
readme = "README.md"
authors = [
    { name = "akennedy", email = "andrewjacobkennedy@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pillow>=12.3",
    "pyseq>=0.9.3",
]

[project.scripts]
sprak = "sprak.cli:pack_sprites"

[project.urls]
Homepage = "https://github.com/kennedy0/sprak"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["N"]

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.1",
    "ty>=0.0.69",
]
